name: Push content to storage account

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  TEST_CONTAINER: pvc-4f616eec-0822-4328-934f-0e8db1e31b31
  TEST_ACCOUNT_NAME: t79takssst01
  PROD_CONTAINER:
  PROD_ACCOUNT_NAME:

jobs:
  copyTestContent:
    if: ${{ startsWith(github.ref, 'refs/tags/v') == false }}
    name: Copy Test Content
    environment: test
    runs-on:
      group: self-hosted-test-aks
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            # Decode the base64 SAS token so GitHub does not mask it
            SAS=$(echo "${{ secrets.TEST_SAS_TOKEN_B64 }}" | base64 -d)

            az storage blob sync \
              --account-name ${{ env.TEST_ACCOUNT_NAME }} \
              --container ${{ env.TEST_CONTAINER }} \
              --destination html \
              --sas-token "$SAS" \
              --source . \
              --exclude-path ".*" \
              --exclude-pattern ".*;CNAME"
